"""Report generation — Markdown, PDF, and JSON."""

import json
import os
import re
from datetime import datetime

from .state import session_log, discovered_hosts, RESULTS_DIR, timestamp
from .recommendations import analyze_session, SEVERITY_ORDER


# ── Markdown — professional security assessment layout ─────────────────────

_SEVERITY_BADGE = {
    "CRITICAL": "[CRITICAL]",
    "HIGH":     "[HIGH]    ",
    "MEDIUM":   "[MEDIUM]  ",
    "LOW":      "[LOW]     ",
    "INFO":     "[INFO]    ",
}


def _risk_narrative(tier: str, total: int, counts: dict) -> str:
    """One-paragraph executive narrative driven by the overall tier."""
    crit = counts.get("CRITICAL", 0)
    high = counts.get("HIGH", 0)
    med = counts.get("MEDIUM", 0)
    if tier == "CRITICAL":
        return (
            f"The overall risk posture is **CRITICAL**. This assessment surfaced {total} finding(s) "
            f"across the in-scope hosts, including {crit} critical and {high} high-severity issue(s). "
            f"Immediate remediation of the critical findings is required; the affected hosts should be "
            f"considered actively at risk until the issues listed below are resolved."
        )
    if tier == "HIGH":
        return (
            f"The overall risk posture is **HIGH**. {high} high-severity and {med} medium-severity "
            f"finding(s) were identified. These should be addressed as part of the next scheduled "
            f"maintenance window; some findings may be exploitable by unauthenticated attackers."
        )
    if tier == "MEDIUM":
        return (
            f"The overall risk posture is **MEDIUM**. The assessment identified {med} medium-severity "
            f"finding(s) and no confirmed critical or high issues. Address the findings below in the "
            f"course of routine patching and configuration hardening."
        )
    if tier == "LOW":
        return (
            f"The overall risk posture is **LOW**. No critical, high, or medium-severity findings were "
            f"identified. The observations below are informational and represent general hardening "
            f"opportunities."
        )
    return (
        "The scan completed successfully but no actionable findings were generated by the rules engine. "
        "This typically means no open ports, services, or CVEs matched the assessment ruleset."
    )


def build_markdown() -> str:
    """Build a professional security-assessment Markdown report."""
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    analysis = analyze_session()
    md: list[str] = []

    # ── Title / metadata ──
    md.append("# Network Security Assessment Report")
    md.append("")
    md.append(f"**Assessment Date:** {now}")
    md.append(f"**Tool:** Network Recon (nmap wrapper)")
    md.append(f"**Total Scans Performed:** {len(session_log)}")
    md.append("")
    md.append("---")
    md.append("")

    # ── Executive Summary ──
    md.append("## 1. Executive Summary")
    md.append("")
    md.append(_risk_narrative(
        analysis["overall_tier"],
        analysis["total_findings"],
        analysis["severity_counts"],
    ))
    md.append("")

    md.append("### 1.1 Findings by Severity")
    md.append("")
    md.append("| Severity | Count |")
    md.append("|----------|-------|")
    for sev in SEVERITY_ORDER:
        count = analysis["severity_counts"].get(sev, 0)
        if count or sev in ("CRITICAL", "HIGH", "MEDIUM"):
            md.append(f"| {sev} | {count} |")
    md.append(f"| **TOTAL** | **{analysis['total_findings']}** |")
    md.append("")

    md.append(f"**Overall Risk Level:** {analysis['overall_tier']}")
    md.append("")
    md.append("---")
    md.append("")

    # ── Scope & Methodology ──
    md.append("## 2. Scope & Methodology")
    md.append("")
    md.append("### 2.1 Scope")
    md.append("")
    if discovered_hosts:
        md.append(f"{len(discovered_hosts)} host(s) were identified as live and in-scope for detailed analysis:")
        md.append("")
        md.append("| # | IP | Hostname | Vendor / MAC |")
        md.append("|---|-----|----------|---------------|")
        for idx, h in enumerate(discovered_hosts, 1):
            hostname = h.get("hostname") or "-"
            vendor = h.get("vendor") or h.get("mac") or "-"
            md.append(f"| {idx} | {h['ip']} | {hostname} | {vendor} |")
        md.append("")
    else:
        targets = sorted({e.get("target") for e in session_log if e.get("target")})
        if targets:
            md.append("The following targets were specified for assessment:")
            md.append("")
            for t in targets:
                md.append(f"- {t}")
            md.append("")

    md.append("### 2.2 Methodology")
    md.append("")
    md.append(
        "The assessment used nmap-based active reconnaissance with the following techniques, "
        "depending on which scan modes were invoked during the session:"
    )
    md.append("")
    md.append("- **Host discovery** (`-sn`): ICMP/ARP ping sweep to identify live hosts on the target network.")
    md.append("- **Port enumeration** (`-p-`, `-sS`): Full TCP port scan using SYN probes.")
    md.append("- **Service and version detection** (`-sV`): Probe-based identification of service banners and versions.")
    md.append("- **Operating system fingerprinting** (`-O`): TCP/IP stack-based OS identification.")
    md.append("- **Vulnerability enumeration** (`--script vuln,vulners,exploit`): Nmap Scripting Engine (NSE) active checks for known CVEs and misconfigurations.")
    md.append("")
    md.append(
        "Findings were then processed by a rules-based analysis engine which correlates open ports, "
        "service banners, detected OS, CVE matches, and NSE vuln-check results against a curated list "
        "of known-risky services, end-of-life software, and default misconfigurations. Each finding is "
        "assigned a severity rating (CRITICAL / HIGH / MEDIUM / LOW / INFO) along with a human-written "
        "description and recommended remediation."
    )
    md.append("")
    md.append("### 2.3 Severity Rating Criteria")
    md.append("")
    md.append("| Rating | Definition |")
    md.append("|--------|------------|")
    md.append("| CRITICAL | Confirmed vulnerability, unauthenticated RCE, plaintext credentials on a reachable service, or default-credential database exposed to untrusted networks. Immediate action required. |")
    md.append("| HIGH | Serious exposure requiring prompt remediation: end-of-life software with known CVEs, exposed management interfaces, weak authentication protocols. |")
    md.append("| MEDIUM | Meaningful hardening issue: information leakage, deprecated protocols, weak configurations that enable secondary attacks. |")
    md.append("| LOW | Informational exposure: expected services that still warrant review for least-privilege configuration. |")
    md.append("| INFO | Observation with no direct security impact. |")
    md.append("")
    md.append("---")
    md.append("")

    # ── Host Risk Matrix ──
    hosts_with_findings = analysis["hosts"]
    if hosts_with_findings:
        md.append("## 3. Host Risk Matrix")
        md.append("")
        md.append("| Host | Hostname / Vendor | Risk Tier | Score | Open Ports | CVEs | Findings |")
        md.append("|------|-------------------|-----------|-------|------------|------|----------|")
        for h in hosts_with_findings:
            label = h["hostname"] or h["vendor"] or "-"
            md.append(
                f"| {h['host']} | {label} | {h['tier']} | {h['score']} | "
                f"{h['open_port_count']} | {h['cve_count']} | {len(h['findings'])} |"
            )
        md.append("")
        md.append("*Host risk tiers are derived from the worst-severity finding on each host. "
                  "Scores are a weighted sum of all findings (CRITICAL=10, HIGH=5, MEDIUM=2, LOW=0.5).*")
        md.append("")
        md.append("---")
        md.append("")

    # ── Detailed Findings per Host ──
    if any(h["findings"] for h in hosts_with_findings):
        md.append("## 4. Detailed Findings")
        md.append("")
        md.append(
            "Findings are grouped by host, ordered by severity. Each finding includes a description "
            "of the issue, the evidence observed, and a specific remediation recommendation."
        )
        md.append("")

        for h in hosts_with_findings:
            if not h["findings"]:
                continue

            label_parts = [h["host"]]
            if h["hostname"]:
                label_parts.append(h["hostname"])
            if h["vendor"]:
                label_parts.append(h["vendor"])
            header_label = " — ".join(label_parts)

            md.append(f"### 4.{hosts_with_findings.index(h) + 1} {header_label}")
            md.append("")
            md.append(f"- **Risk Tier:** {h['tier']}")
            md.append(f"- **Weighted Score:** {h['score']}")
            md.append(f"- **Open Ports:** {h['open_port_count']}")
            md.append(f"- **CVE Catalog Matches:** {h['cve_count']}")
            md.append("")

            for idx, finding in enumerate(h["findings"], 1):
                md.append(f"### Finding {idx}: [{finding['severity']}] {finding['title']}")
                md.append("")
                md.append(f"- **Endpoint:** `{finding['endpoint']}`")
                md.append(f"- **Evidence:** {finding['evidence']}")
                md.append("")
                md.append("**Description:**")
                md.append("")
                md.append(finding["description"])
                md.append("")
                md.append("**Recommendation:**")
                md.append("")
                md.append(finding["recommendation"])
                md.append("")

            md.append("---")
            md.append("")

    # ── Remediation Roadmap ──
    if analysis["total_findings"]:
        md.append("## 5. Remediation Roadmap")
        md.append("")
        md.append(
            "The following priority list consolidates every finding across all hosts, ordered by "
            "severity. Items should be addressed top-to-bottom."
        )
        md.append("")

        flat: list[dict] = []
        for h in hosts_with_findings:
            for f in h["findings"]:
                flat.append(f)
        flat.sort(key=lambda f: (SEVERITY_ORDER.index(f["severity"]), f["title"]))

        priority = 1
        current_sev = None
        for finding in flat:
            if finding["severity"] != current_sev:
                if current_sev is not None:
                    md.append("")
                current_sev = finding["severity"]
                md.append(f"### {current_sev} priority")
                md.append("")
            md.append(f"{priority}. **{finding['title']}** — `{finding['endpoint']}`")
            md.append(f"   - {finding['recommendation']}")
            priority += 1
        md.append("")
        md.append("---")
        md.append("")

    # ── Technical Appendix ──
    md.append("## 6. Technical Appendix")
    md.append("")
    md.append("This appendix contains the raw technical data collected during the assessment.")
    md.append("")

    # A. CVE list
    all_cves = sorted({c for h in hosts_with_findings for c in [] for _ in range(0)})
    all_cves = sorted({cve for entry in session_log
                       for cve in entry.get("findings", {}).get("cves", []) or []})
    if all_cves:
        md.append("### 6.1 CVE Catalog Matches")
        md.append("")
        md.append(
            "The following CVE identifiers were reported by the nmap `vulners` script based on "
            "service-banner matching. These represent *potential* issues associated with the detected "
            "software versions and should be confirmed against vendor advisories before assuming "
            "exploitability."
        )
        md.append("")
        md.append("| # | CVE ID |")
        md.append("|---|--------|")
        for idx, cve in enumerate(all_cves, 1):
            md.append(f"| {idx} | {cve} |")
        md.append("")

    # B. Open ports (aggregated)
    all_ports = []
    for entry in session_log:
        all_ports.extend(entry.get("findings", {}).get("open_ports", []) or [])
    unique_ports = sorted(set(all_ports))
    if unique_ports:
        md.append("### 6.2 Open Ports & Services Inventory")
        md.append("")
        md.append("| Port | State | Service / Version |")
        md.append("|------|-------|-------------------|")
        for p in unique_ports:
            parts = p.split(None, 2)
            if len(parts) >= 3:
                md.append(f"| {parts[0]} | {parts[1]} | {parts[2]} |")
            else:
                md.append(f"| {p} | | |")
        md.append("")

    # C. OS detections
    all_os = sorted({os_line for entry in session_log
                     for os_line in entry.get("findings", {}).get("os_detected", []) or []})
    if all_os:
        md.append("### 6.3 Operating Systems Detected")
        md.append("")
        for os_line in all_os:
            md.append(f"- {os_line}")
        md.append("")

    # D. Per-scan log
    md.append("### 6.4 Scan Log")
    md.append("")
    md.append("Chronological log of the individual nmap invocations performed during this session.")
    md.append("")
    for i, entry in enumerate(session_log, 1):
        status = "Success" if entry.get("return_code") == 0 else "Failed / Interrupted"
        md.append(f"**Scan #{i}:** {entry.get('description', '(no description)')}")
        md.append("")
        md.append(f"- **Time:** {entry.get('time', '-')}")
        md.append(f"- **Status:** {status}")
        md.append(f"- **Target:** {entry.get('target', '-')}")
        md.append("- **Command:**")
        md.append("  ```")
        md.append(f"  {entry.get('command', '-')}")
        md.append("  ```")
        if entry.get("output_file"):
            md.append(f"- **Raw output:** `{entry['output_file']}`")

        f = entry.get("findings", {})
        if isinstance(f, dict):
            if f.get("hosts_up"):
                md.append(f"- **Hosts up:** {f['hosts_up']}")
            if f.get("open_ports"):
                md.append(f"- **Open ports:** {len(f['open_ports'])}")
            if f.get("cves"):
                md.append(f"- **CVE catalog matches:** {len(f['cves'])}")
            scan_passed = f.get("vulns_passed", 0)
            scan_failed = f.get("vulns_failed") or []
            scan_likely = f.get("vulns_likely") or []
            if scan_failed or scan_likely:
                md.append("- **NSE vulnerability checks:**")
                for v in scan_failed:
                    md.append(f"  - [VULNERABLE] `{v['script']}` on `{v['endpoint']}` -> {v['description']}")
                for v in scan_likely:
                    md.append(f"  - [LIKELY] `{v['script']}` on `{v['endpoint']}` -> {v['description']}")
                if scan_passed:
                    md.append(f"  - *({scan_passed} additional checks passed)*")
            elif scan_passed:
                md.append(f"- **NSE vulnerability checks:** {scan_passed} ran, all passed")
        md.append("")

    md.append("---")
    md.append("")

    # ── Disclaimer ──
    md.append("## 7. Disclaimer")
    md.append("")
    md.append(
        "This assessment was generated by an automated tool and reflects the state of the target(s) "
        "at the time of scanning. It is not a substitute for a manual penetration test or a full "
        "code/configuration audit. Findings based on service-banner version matching (CVE catalog) may "
        "produce false positives if the vendor has backported security fixes without changing the "
        "advertised version string."
    )
    md.append("")
    md.append(
        "**Authorization:** Active network scanning of systems you do not own or have explicit "
        "written permission to test is illegal in most jurisdictions. This report should only be "
        "distributed to parties with a legitimate need to know."
    )
    md.append("")
    md.append("---")
    md.append("")
    md.append("*Report generated by Network Recon*")

    return "\n".join(md)


# ── JSON ────────────────────────────────────────────────────────────────────

def build_json() -> str:
    """Build a JSON report from session_log."""
    data = {
        "generated": datetime.now().isoformat(),
        "total_scans": len(session_log),
        "discovered_hosts": discovered_hosts,
        "scans": session_log,
    }
    return json.dumps(data, indent=2)


# ── PDF ─────────────────────────────────────────────────────────────────────

# Color scheme (R, G, B). Used throughout generate_pdf.
_COLOR_TITLE        = (15, 50, 95)      # deep navy for cover title
_COLOR_HEADER       = (24, 78, 119)     # dark blue for ## headers
_COLOR_SUBHEADER    = (60, 110, 150)    # medium blue for ### headers
_COLOR_DEFAULT      = (40, 40, 40)      # near-black body text
_COLOR_DIM          = (110, 110, 110)   # captions / footers
_COLOR_RULE         = (180, 195, 215)   # horizontal rule line
_COLOR_TABLE_HEAD   = (220, 232, 244)   # light blue table header fill
_COLOR_TABLE_BORDER = (170, 180, 200)
_COLOR_CODE_BG      = (244, 246, 250)
_COLOR_CRITICAL     = (190, 30, 30)     # CRITICAL / VULNERABLE / CVE-
_COLOR_HIGH         = (205, 95, 25)
_COLOR_MEDIUM       = (190, 150, 30)
_COLOR_LOW          = (50, 130, 65)     # success / LOW
_COLOR_INFO         = _COLOR_SUBHEADER

# Severity label -> color. Used ONLY for explicit [CRITICAL], [HIGH], etc.
# labels and the single-word cells in the severity summary table.
# Body paragraphs stay black — no inline color.
_SEVERITY_COLORS = {
    "CRITICAL": _COLOR_CRITICAL,
    "HIGH":     _COLOR_HIGH,
    "MEDIUM":   _COLOR_MEDIUM,
    "LOW":      _COLOR_LOW,
    "INFO":     _COLOR_DIM,
}


def _severity_label_color(text: str):
    """Return the (r,g,b) for an EXACT severity word, or None.

    Only matches when the cell/label is exactly 'CRITICAL', 'HIGH', 'MEDIUM',
    'LOW', or 'INFO' — stops the body-text red-coloring problem.
    """
    return _SEVERITY_COLORS.get(text.strip().upper())


def _extract_severity_badge(line: str):
    """If line starts with '[SEVERITY] rest...', return (severity, rest) else (None, line)."""
    m = re.match(r"^\[(CRITICAL|HIGH|MEDIUM|LOW|INFO)\]\s*(.*)", line)
    if m:
        return m.group(1), m.group(2)
    return None, line


def _draw_severity_badge(pdf, severity: str):
    """Draw a small colored pill with the severity text, advance the cursor.

    Keeps the body line text black — only the badge itself is colored. Much
    cleaner than painting the entire line in red bold.
    """
    color = _SEVERITY_COLORS.get(severity.upper(), _COLOR_DIM)
    pdf.set_font("Helvetica", "B", 8)
    text = f" {severity.upper()} "
    w = pdf.get_string_width(text) + 2
    pdf.set_fill_color(*color)
    pdf.set_text_color(255, 255, 255)
    pdf.cell(w, 5, text, border=0, align="C", fill=True)
    pdf.set_text_color(*_COLOR_DEFAULT)
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(2, 5, "")  # small gap


def _table_row_height(pdf, cells: list[str], col_widths: list[float], line_h: float) -> float:
    """Measure how tall a row needs to be so every cell fits, wrapped."""
    max_lines = 1
    for cell, w in zip(cells, col_widths):
        # Approximate: split by manually inserted \n then by measured width
        text = _safe(cell)
        if not text:
            continue
        # get_string_width is in the current font metric (assumed set by caller)
        n_lines = max(1, pdf.multi_cell(
            w, line_h, text, border=0, align="L",
            split_only=True, new_x="RIGHT", new_y="TOP",
        ).__len__() if hasattr(pdf, "multi_cell") else 1)
        if n_lines > max_lines:
            max_lines = n_lines
    return max_lines * line_h


def _render_table(pdf, rows: list[list[str]]):
    """Render a markdown table with proportional column widths and wrapped cells."""
    if not rows:
        return

    usable = pdf.w - pdf.l_margin - pdf.r_margin
    col_count = max(len(r) for r in rows)

    # Compute a "natural" width for each column = max string width of any cell in it
    pdf.set_font("Helvetica", "", 9)
    natural_w = [0.0] * col_count
    for row in rows:
        for i, cell in enumerate(row):
            if i >= col_count:
                continue
            # Strip markdown bold markers for measurement
            clean = re.sub(r"\*\*(.+?)\*\*", r"\1", cell)
            clean = re.sub(r"`(.+?)`", r"\1", clean)
            w = pdf.get_string_width(_safe(clean)) + 4  # padding
            if w > natural_w[i]:
                natural_w[i] = w

    total_natural = sum(natural_w)
    if total_natural <= usable:
        # Everything fits naturally — pad columns proportionally to fill width
        extra = usable - total_natural
        col_widths = [w + extra / col_count for w in natural_w]
    else:
        # Scale everything down proportionally, but cap the scale so even the
        # widest columns still fit by wrapping
        scale = usable / total_natural
        col_widths = [max(w * scale, usable / (col_count * 3)) for w in natural_w]
        # Re-normalize to exactly usable width
        s = sum(col_widths)
        col_widths = [w * (usable / s) for w in col_widths]

    line_h = 5

    # Header row
    header = rows[0]
    pdf.set_fill_color(*_COLOR_TABLE_HEAD)
    pdf.set_text_color(*_COLOR_HEADER)
    pdf.set_font("Helvetica", "B", 9)
    pdf.set_draw_color(*_COLOR_TABLE_BORDER)

    # Measure header height (wrapped)
    header_h = _wrapped_row_height(pdf, header, col_widths, line_h)
    _render_row(pdf, header, col_widths, header_h, line_h, fill=True, bold=True)

    # Body rows
    pdf.set_text_color(*_COLOR_DEFAULT)
    pdf.set_font("Helvetica", "", 9)
    for row in rows[1:]:
        row_h = _wrapped_row_height(pdf, row, col_widths, line_h)
        # Page break guard
        if pdf.get_y() + row_h > pdf.h - pdf.b_margin:
            pdf.add_page()
        _render_row(pdf, row, col_widths, row_h, line_h, fill=False, bold=False)

    pdf.set_draw_color(*_COLOR_RULE)


def _wrapped_row_height(pdf, cells: list[str], col_widths: list[float], line_h: float) -> float:
    """Calculate the row height needed to fit every cell's wrapped content."""
    max_lines = 1
    for i, cell in enumerate(cells):
        if i >= len(col_widths):
            break
        clean = re.sub(r"\*\*(.+?)\*\*", r"\1", cell)
        clean = re.sub(r"`(.+?)`", r"\1", clean)
        text = _safe(clean)
        if not text.strip():
            continue
        # Count wrapped lines: how many times will this text break at col_widths[i]?
        # Use fpdf2's built-in: split_only returns the lines list.
        try:
            lines = pdf.multi_cell(
                col_widths[i] - 2, line_h, text,
                split_only=True, new_x="RIGHT", new_y="TOP",
            )
            n = max(1, len(lines))
        except Exception:
            n = 1
        if n > max_lines:
            max_lines = n
    return max_lines * line_h


def _render_row(pdf, cells: list[str], col_widths: list[float], row_h: float,
                line_h: float, fill: bool, bold: bool):
    """Draw a single row with wrapped cells at a fixed total height."""
    x_start = pdf.get_x()
    y_start = pdf.get_y()
    for i in range(len(col_widths)):
        cell_text = cells[i] if i < len(cells) else ""
        clean = re.sub(r"\*\*(.+?)\*\*", r"\1", cell_text)
        clean = re.sub(r"`(.+?)`", r"\1", clean)
        text = _safe(clean).strip()

        # Per-cell color: severity words in the summary table, nothing else
        sev_color = _severity_label_color(text)
        if sev_color:
            pdf.set_text_color(*sev_color)
            pdf.set_font("Helvetica", "B", 9)
        else:
            if bold:
                pdf.set_font("Helvetica", "B", 9)
                pdf.set_text_color(*_COLOR_HEADER)
            else:
                pdf.set_font("Helvetica", "", 9)
                pdf.set_text_color(*_COLOR_DEFAULT)

        x_cell = x_start + sum(col_widths[:i])
        pdf.set_xy(x_cell, y_start)
        # Draw border manually so we can control height
        pdf.rect(x_cell, y_start, col_widths[i], row_h)
        if fill:
            pdf.set_fill_color(*_COLOR_TABLE_HEAD)
            pdf.rect(x_cell, y_start, col_widths[i], row_h, style="F")
            pdf.rect(x_cell, y_start, col_widths[i], row_h)
        # Draw the text wrapped inside the cell with a small top padding
        pdf.set_xy(x_cell + 1, y_start + 0.5)
        pdf.multi_cell(
            col_widths[i] - 2, line_h, text,
            border=0, align="L",
            new_x="RIGHT", new_y="TOP",
        )

    pdf.set_xy(x_start, y_start + row_h)
    pdf.set_text_color(*_COLOR_DEFAULT)
    pdf.set_font("Helvetica", "", 10)


def generate_pdf(md_content: str, pdf_path: str):
    """Convert the report content into a styled PDF with color highlighting."""
    try:
        from fpdf import FPDF
    except ImportError as e:
        raise ImportError(
            "fpdf2 is required for PDF reports. Install with: pip install fpdf2"
        ) from e

    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    # ── Cover / title ──
    pdf.set_text_color(*_COLOR_TITLE)
    pdf.set_font("Helvetica", "B", 24)
    pdf.cell(0, 15, "Network Security", new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.cell(0, 12, "Assessment Report", new_x="LMARGIN", new_y="NEXT", align="C")

    pdf.set_text_color(*_COLOR_DIM)
    pdf.set_font("Helvetica", "", 11)
    pdf.cell(
        0, 6,
        f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        new_x="LMARGIN", new_y="NEXT", align="C",
    )
    pdf.ln(3)

    # Decorative rule under title
    pdf.set_draw_color(*_COLOR_HEADER)
    pdf.set_line_width(0.6)
    y = pdf.get_y()
    pdf.line(pdf.l_margin + 30, y, pdf.w - pdf.r_margin - 30, y)
    pdf.set_line_width(0.2)
    pdf.ln(6)

    # Reset to body defaults
    pdf.set_text_color(*_COLOR_DEFAULT)
    pdf.set_font("Helvetica", "", 10)

    in_code_block = False

    # Professional spacing: 10pt body with ~1.3x leading (line height 5.2pt)
    BODY_LH = 5.2
    BODY_SIZE = 10
    PARAGRAPH_GAP = 2.5
    MAX_LINE_CHARS = 800

    # Pre-collect consecutive table rows so _render_table can size columns
    # correctly (requires all rows at once).
    table_buffer: list[list[str]] = []

    def flush_table():
        if table_buffer:
            _render_table(pdf, table_buffer[:])
            table_buffer.clear()
            pdf.ln(PARAGRAPH_GAP)
            pdf.set_text_color(*_COLOR_DEFAULT)
            pdf.set_font("Helvetica", "", BODY_SIZE)

    def write_body_paragraph(text: str, lh: float = BODY_LH, size: int = BODY_SIZE,
                              bold: bool = False, italic: bool = False,
                              color=None):
        pdf.set_text_color(*(color or _COLOR_DEFAULT))
        style = ("B" if bold else "") + ("I" if italic else "")
        pdf.set_font("Helvetica", style, size)
        pdf.multi_cell(0, lh, _safe(text), new_x="LMARGIN", new_y="NEXT")
        pdf.set_text_color(*_COLOR_DEFAULT)
        pdf.set_font("Helvetica", "", BODY_SIZE)

    for raw_line in md_content.splitlines():
        if len(raw_line) > MAX_LINE_CHARS:
            line = raw_line[:MAX_LINE_CHARS] + f" ... [+{len(raw_line) - MAX_LINE_CHARS} chars truncated]"
        else:
            line = raw_line

        # Flush the table buffer when we leave a run of pipe rows
        if not (line.strip().startswith("|") and line.strip().endswith("|")):
            flush_table()

        if line.startswith("# Network Security") or line.startswith("# Network Recon"):
            continue

        # Horizontal rule
        if line.strip() == "---":
            pdf.ln(2)
            pdf.set_draw_color(*_COLOR_RULE)
            y = pdf.get_y()
            pdf.line(pdf.l_margin, y, pdf.w - pdf.r_margin, y)
            pdf.ln(4)
            continue

        # Code block toggle
        if line.strip().startswith("```"):
            in_code_block = not in_code_block
            if in_code_block:
                pdf.set_font("Courier", "", 8)
            else:
                pdf.set_font("Helvetica", "", BODY_SIZE)
            continue

        # Code block content
        if in_code_block:
            pdf.set_fill_color(*_COLOR_CODE_BG)
            pdf.set_text_color(*_COLOR_DEFAULT)
            pdf.set_font("Courier", "", 8)
            safe = _safe(line)
            pdf.cell(0, 5, f"  {safe}", new_x="LMARGIN", new_y="NEXT", fill=True)
            continue

        # ## Headers — dark blue, bold, 14pt, with thin blue underline
        if line.startswith("## "):
            pdf.ln(4)
            pdf.set_text_color(*_COLOR_HEADER)
            pdf.set_font("Helvetica", "B", 14)
            pdf.cell(0, 8, _safe(line[3:]), new_x="LMARGIN", new_y="NEXT")
            pdf.set_draw_color(*_COLOR_HEADER)
            pdf.set_line_width(0.4)
            y = pdf.get_y()
            pdf.line(pdf.l_margin, y, pdf.l_margin + 60, y)
            pdf.set_line_width(0.2)
            pdf.ln(3)
            pdf.set_text_color(*_COLOR_DEFAULT)
            pdf.set_font("Helvetica", "", BODY_SIZE)
            continue

        # ### Sub-headers — medium blue, bold, 11pt
        if line.startswith("### "):
            pdf.ln(3)
            pdf.set_text_color(*_COLOR_SUBHEADER)
            pdf.set_font("Helvetica", "B", 11)
            pdf.cell(0, 6, _safe(line[4:]), new_x="LMARGIN", new_y="NEXT")
            pdf.ln(1)
            pdf.set_text_color(*_COLOR_DEFAULT)
            pdf.set_font("Helvetica", "", BODY_SIZE)
            continue

        # Table separator (skip)
        if line.strip().startswith("|--") or line.strip().startswith("|-"):
            continue

        # Table row: buffer it, render on flush
        if line.strip().startswith("|") and line.strip().endswith("|"):
            cells = [c.strip() for c in line.strip().strip("|").split("|")]
            table_buffer.append(cells)
            continue

        # Bullet points — body text black, severity label colored with badge
        if line.startswith("- "):
            text = re.sub(r"\*\*(.+?)\*\*", r"\1", line[2:])
            text = re.sub(r"`(.+?)`", r"\1", text)
            sev, rest = _extract_severity_badge(text)
            if sev:
                pdf.cell(4, BODY_LH, "-")
                _draw_severity_badge(pdf, sev)
                pdf.set_font("Helvetica", "", BODY_SIZE)
                pdf.set_text_color(*_COLOR_DEFAULT)
                pdf.multi_cell(0, BODY_LH, _safe(rest), new_x="LMARGIN", new_y="NEXT")
            else:
                pdf.set_font("Helvetica", "", BODY_SIZE)
                pdf.set_text_color(*_COLOR_DEFAULT)
                pdf.multi_cell(0, BODY_LH, "- " + _safe(text),
                               new_x="LMARGIN", new_y="NEXT")
            continue

        if line.startswith("  - "):
            text = line[4:]
            text = re.sub(r"\*\*(.+?)\*\*", r"\1", text)
            text = re.sub(r"`(.+?)`", r"\1", text)
            pdf.set_font("Helvetica", "", 9)
            pdf.set_text_color(*_COLOR_DEFAULT)
            pdf.multi_cell(0, 4.8, "    - " + _safe(text),
                           new_x="LMARGIN", new_y="NEXT")
            pdf.set_font("Helvetica", "", BODY_SIZE)
            continue

        # Lines that start with a bold label followed by value
        # (e.g. "**Risk Tier:** CRITICAL"). Keep the label dark-blue bold,
        # the value black. If the value is a severity word, show it as a badge.
        bold_match = re.match(r"\*\*(.+?)\*\*\s*(.*)", line)
        if bold_match:
            label = _safe(bold_match.group(1))
            value = bold_match.group(2).strip()
            value = re.sub(r"`(.+?)`", r"\1", value)

            pdf.set_text_color(*_COLOR_HEADER)
            pdf.set_font("Helvetica", "B", BODY_SIZE)
            label_w = pdf.get_string_width(label + " ") + 1
            pdf.cell(label_w, BODY_LH, label)

            sev_color = _severity_label_color(value) if value else None
            if sev_color:
                _draw_severity_badge(pdf, value)
                pdf.cell(0, BODY_LH, "", new_x="LMARGIN", new_y="NEXT")
            else:
                pdf.set_text_color(*_COLOR_DEFAULT)
                pdf.set_font("Helvetica", "", BODY_SIZE)
                pdf.multi_cell(0, BODY_LH, _safe(value),
                               new_x="LMARGIN", new_y="NEXT")
            continue

        # Italic / footer caption
        if line.startswith("*") and line.endswith("*") and len(line) > 2:
            pdf.ln(2)
            pdf.set_text_color(*_COLOR_DIM)
            pdf.set_font("Helvetica", "I", 8)
            pdf.multi_cell(0, 4.5, _safe(line.strip("*")),
                           new_x="LMARGIN", new_y="NEXT", align="C")
            pdf.set_text_color(*_COLOR_DEFAULT)
            pdf.set_font("Helvetica", "", BODY_SIZE)
            continue

        # Regular paragraph — black, no inline color
        if line.strip():
            text = re.sub(r"\*\*(.+?)\*\*", r"\1", line)
            text = re.sub(r"`(.+?)`", r"\1", text)
            pdf.set_text_color(*_COLOR_DEFAULT)
            pdf.set_font("Helvetica", "", BODY_SIZE)
            pdf.multi_cell(0, BODY_LH, _safe(text),
                           new_x="LMARGIN", new_y="NEXT")
            pdf.ln(PARAGRAPH_GAP)

    flush_table()  # flush any trailing table
    pdf.output(pdf_path)


# Common Unicode chars used in our markdown that latin-1 can't encode.
# Translate to readable ASCII equivalents instead of letting them turn into "?".
_UNICODE_FALLBACKS = {
    "\u2022": "*",   # bullet
    "\u2014": "-",   # em dash
    "\u2013": "-",   # en dash
    "\u2192": "->",  # rightwards arrow
    "\u2190": "<-",  # leftwards arrow
    "\u2713": "v",   # check mark
    "\u2717": "x",   # cross mark
    "\u2705": "[OK]",
    "\u274C": "[X]",
    "\u26A0": "!",   # warning
    "\u2026": "...", # ellipsis
    "\u201C": '"', "\u201D": '"',  # smart quotes
    "\u2018": "'", "\u2019": "'",
    # Box drawing chars used in menu banners / tables
    "\u2550": "=", "\u2551": "|",
    "\u2500": "-", "\u2502": "|",
    "\u250C": "+", "\u2510": "+",
    "\u2514": "+", "\u2518": "+",
    "\u251C": "+", "\u2524": "+",
    "\u252C": "+", "\u2534": "+", "\u253C": "+",
}


def _safe(text: str) -> str:
    """Make text safe for latin-1 PDF encoding.

    First substitute common Unicode chars (bullets, em dashes, box drawing)
    with ASCII equivalents so they render as expected, then fall back to
    'replace' for anything else (becomes '?').
    """
    for unicode_char, ascii_char in _UNICODE_FALLBACKS.items():
        if unicode_char in text:
            text = text.replace(unicode_char, ascii_char)
    return text.encode("latin-1", "replace").decode("latin-1")


# ── Generate all reports ────────────────────────────────────────────────────

def generate_reports():
    """Generate .md, .pdf, and .json session reports."""
    if not session_log:
        print("\n[*] No scans were performed this session.")
        return

    os.makedirs(RESULTS_DIR, exist_ok=True)
    ts = timestamp()

    # Markdown
    md_content = build_markdown()
    md_path = os.path.join(RESULTS_DIR, f"report_{ts}.md")
    with open(md_path, "w") as fh:
        fh.write(md_content)
    print(f"\n[+] Markdown report: {md_path}")

    # JSON
    json_content = build_json()
    json_path = os.path.join(RESULTS_DIR, f"report_{ts}.json")
    with open(json_path, "w") as fh:
        fh.write(json_content)
    print(f"[+] JSON report:     {json_path}")

    # PDF
    pdf_path = os.path.join(RESULTS_DIR, f"report_{ts}.pdf")
    try:
        generate_pdf(md_content, pdf_path)
        print(f"[+] PDF report:      {pdf_path}")
    except Exception as e:
        import traceback
        print(f"[!] PDF generation failed: {type(e).__name__}: {e}")
        print("[!] Full traceback:")
        traceback.print_exc()
        print("[!] Markdown and JSON reports were still generated above.")

    # Terminal summary
    print(f"\n{'=' * 60}")
    print(md_content)
    print(f"{'=' * 60}")
