"""Report generation — Markdown, PDF, and JSON."""

import json
import os
import re
from datetime import datetime

from .state import session_log, discovered_hosts, RESULTS_DIR, timestamp

try:
    from fpdf import FPDF
    HAS_FPDF = True
except ImportError:
    HAS_FPDF = False


# ── Markdown ────────────────────────────────────────────────────────────────

def build_markdown() -> str:
    """Build a Markdown report from session_log."""
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    md = []

    md.append("# Network Recon — Session Report")
    md.append("")
    md.append(f"**Generated:** {now}")
    md.append(f"**Total Scans:** {len(session_log)}")
    md.append("")
    md.append("---")
    md.append("")

    # Aggregate stats
    total_hosts = 0
    all_ports = []
    all_cves = []
    all_vulns = []
    all_os = []
    all_services = []

    for entry in session_log:
        f = entry.get("findings", {})
        total_hosts += f.get("hosts_up", 0)
        all_ports.extend(f.get("open_ports", []))
        all_cves.extend(f.get("cves", []))
        all_vulns.extend(f.get("vulns", []))
        all_os.extend(f.get("os_detected", []))
        all_services.extend(f.get("services", []))

    # Executive summary
    md.append("## Executive Summary")
    md.append("")
    md.append("| Metric | Count |")
    md.append("|--------|-------|")
    md.append(f"| Scans Performed | {len(session_log)} |")
    md.append(f"| Hosts Discovered | {total_hosts} |")
    md.append(f"| Open Ports Found | {len(all_ports)} |")
    md.append(f"| CVEs Identified | {len(set(all_cves))} |")
    md.append(f"| Vulnerabilities | {len(all_vulns)} |")
    md.append("")

    risk = "CRITICAL" if all_cves else ("MEDIUM" if all_ports else "LOW")
    md.append(f"**Overall Risk Level:** {risk}")
    md.append("")
    md.append("---")
    md.append("")

    # Discovered hosts table
    if discovered_hosts:
        md.append("## Discovered Hosts")
        md.append("")
        md.append("| # | IP | Hostname | MAC/Vendor |")
        md.append("|---|-----|----------|------------|")
        for idx, h in enumerate(discovered_hosts, 1):
            hostname = h.get("hostname") or "-"
            vendor = h.get("vendor") or h.get("mac") or "-"
            md.append(f"| {idx} | {h['ip']} | {hostname} | {vendor} |")
        md.append("")
        md.append("---")
        md.append("")

    # CVE summary
    if all_cves:
        md.append("## CVEs Found")
        md.append("")
        unique_cves = sorted(set(all_cves))
        md.append("| # | CVE ID |")
        md.append("|---|--------|")
        for idx, cve in enumerate(unique_cves, 1):
            md.append(f"| {idx} | {cve} |")
        md.append("")
        md.append("---")
        md.append("")

    # OS detection
    if all_os:
        md.append("## Operating Systems Detected")
        md.append("")
        for o in sorted(set(all_os)):
            md.append(f"- {o}")
        md.append("")
        md.append("---")
        md.append("")

    # Open ports & services
    if all_ports:
        md.append("## Open Ports & Services")
        md.append("")
        md.append("| Port | State | Service/Version |")
        md.append("|------|-------|-----------------|")
        for p in sorted(set(all_ports)):
            parts = p.split(None, 2)
            if len(parts) >= 3:
                md.append(f"| {parts[0]} | {parts[1]} | {parts[2]} |")
            else:
                md.append(f"| {p} | | |")
        md.append("")
        md.append("---")
        md.append("")

    # Individual scan details
    md.append("## Scan Details")
    md.append("")

    for i, entry in enumerate(session_log, 1):
        status = "Success" if entry["return_code"] == 0 else "Failed / Interrupted"
        md.append(f"### Scan #{i}: {entry['description']}")
        md.append("")
        md.append(f"- **Time:** {entry['time']}")
        md.append(f"- **Status:** {status}")
        md.append("- **Command:**")
        md.append("  ```")
        md.append(f"  {entry['command']}")
        md.append("  ```")

        if entry.get("output_file"):
            md.append(f"- **Raw output:** `{entry['output_file']}`")

        f = entry.get("findings", {})

        if f.get("hosts"):
            md.append(f"- **Hosts scanned:** {', '.join(f['hosts'])}")
        if f.get("hosts_up"):
            md.append(f"- **Hosts up:** {f['hosts_up']}")
        if f.get("open_ports"):
            md.append(f"- **Open ports:** {len(f['open_ports'])}")
        if f.get("cves"):
            md.append(f"- **CVEs:** {', '.join(f['cves'])}")
        if f.get("vulns"):
            md.append("- **Vulnerabilities:**")
            for v in f["vulns"]:
                md.append(f"  - {v}")

        md.append("")

    md.append("---")
    md.append("")
    md.append("*Report generated by Network Recon*")

    return "\n".join(md)


# ── JSON ────────────────────────────────────────────────────────────────────

def build_json() -> str:
    """Build a JSON report from session_log."""
    data = {
        "generated": datetime.now().isoformat(),
        "total_scans": len(session_log),
        "discovered_hosts": discovered_hosts,
        "scans": session_log,
    }
    return json.dumps(data, indent=2)


# ── PDF ─────────────────────────────────────────────────────────────────────

def generate_pdf(md_content: str, pdf_path: str):
    """Convert the report content into a styled PDF."""
    if not HAS_FPDF:
        raise ImportError("fpdf2 is required for PDF reports. Install with: pip install fpdf2")

    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    # Title
    pdf.set_font("Helvetica", "B", 20)
    pdf.cell(0, 12, "Network Recon", new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.set_font("Helvetica", "", 12)
    pdf.cell(0, 8, "Session Report", new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.set_font("Helvetica", "", 9)
    pdf.cell(
        0, 6,
        f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        new_x="LMARGIN", new_y="NEXT", align="C",
    )
    pdf.ln(6)

    in_code_block = False
    in_table = False

    for line in md_content.splitlines():
        if line.startswith("# Network Recon"):
            continue

        # Horizontal rule
        if line.strip() == "---":
            pdf.ln(2)
            y = pdf.get_y()
            pdf.line(pdf.l_margin, y, pdf.w - pdf.r_margin, y)
            pdf.ln(4)
            in_table = False
            continue

        # Code block toggle
        if line.strip().startswith("```"):
            in_code_block = not in_code_block
            if in_code_block:
                pdf.set_font("Courier", "", 8)
            else:
                pdf.set_font("Helvetica", "", 10)
            continue

        # Code block content
        if in_code_block:
            pdf.set_fill_color(240, 240, 240)
            pdf.set_font("Courier", "", 8)
            safe = _safe(line)
            pdf.cell(0, 5, f"  {safe}", new_x="LMARGIN", new_y="NEXT", fill=True)
            continue

        # Headers
        if line.startswith("## "):
            pdf.ln(4)
            pdf.set_font("Helvetica", "B", 14)
            pdf.cell(0, 8, line[3:], new_x="LMARGIN", new_y="NEXT")
            pdf.ln(2)
            pdf.set_font("Helvetica", "", 10)
            in_table = False
            continue

        if line.startswith("### "):
            pdf.ln(3)
            pdf.set_font("Helvetica", "B", 12)
            pdf.cell(0, 7, line[4:], new_x="LMARGIN", new_y="NEXT")
            pdf.ln(1)
            pdf.set_font("Helvetica", "", 10)
            in_table = False
            continue

        # Table separator (skip)
        if line.strip().startswith("|--") or line.strip().startswith("|-"):
            continue

        # Table rows
        if line.strip().startswith("|") and line.strip().endswith("|"):
            cells = [c.strip() for c in line.strip().strip("|").split("|")]
            col_count = len(cells)
            usable = pdf.w - pdf.l_margin - pdf.r_margin
            col_w = usable / col_count

            if not in_table:
                in_table = True
                pdf.set_font("Helvetica", "B", 9)
                for cell in cells:
                    pdf.cell(col_w, 6, _safe(cell), border=1, align="C")
                pdf.ln()
                pdf.set_font("Helvetica", "", 9)
            else:
                for cell in cells:
                    pdf.cell(col_w, 6, _safe(cell), border=1)
                pdf.ln()
            continue

        if in_table and not line.strip().startswith("|"):
            in_table = False

        # Bullet points
        if line.startswith("- "):
            pdf.set_font("Helvetica", "", 10)
            text = re.sub(r"\*\*(.+?)\*\*", r"\1", line[2:])
            pdf.cell(6, 6, chr(8226))
            pdf.multi_cell(0, 6, _safe(text))
            continue

        if line.startswith("  - "):
            pdf.set_font("Helvetica", "", 9)
            pdf.cell(12, 5, chr(8226))
            pdf.multi_cell(0, 5, _safe(line[4:]))
            continue

        # Bold lines
        bold_match = re.match(r"\*\*(.+?)\*\*\s*(.*)", line)
        if bold_match:
            pdf.set_font("Helvetica", "B", 10)
            label = _safe(bold_match.group(1))
            value = _safe(bold_match.group(2))
            label_w = pdf.get_string_width(label) + 2
            pdf.cell(label_w, 6, label)
            pdf.set_font("Helvetica", "", 10)
            pdf.cell(0, 6, value, new_x="LMARGIN", new_y="NEXT")
            continue

        # Italic / footer
        if line.startswith("*") and line.endswith("*"):
            pdf.ln(4)
            pdf.set_font("Helvetica", "I", 9)
            pdf.cell(0, 6, _safe(line.strip("*")), new_x="LMARGIN", new_y="NEXT", align="C")
            pdf.set_font("Helvetica", "", 10)
            continue

        # Regular text
        if line.strip():
            pdf.set_font("Helvetica", "", 10)
            text = re.sub(r"\*\*(.+?)\*\*", r"\1", line)
            text = re.sub(r"`(.+?)`", r"\1", text)
            pdf.multi_cell(0, 6, _safe(text))

    pdf.output(pdf_path)


def _safe(text: str) -> str:
    """Make text safe for latin-1 PDF encoding."""
    return text.encode("latin-1", "replace").decode("latin-1")


# ── Generate all reports ────────────────────────────────────────────────────

def generate_reports():
    """Generate .md, .pdf, and .json session reports."""
    if not session_log:
        print("\n[*] No scans were performed this session.")
        return

    os.makedirs(RESULTS_DIR, exist_ok=True)
    ts = timestamp()

    # Markdown
    md_content = build_markdown()
    md_path = os.path.join(RESULTS_DIR, f"report_{ts}.md")
    with open(md_path, "w") as fh:
        fh.write(md_content)
    print(f"\n[+] Markdown report: {md_path}")

    # JSON
    json_content = build_json()
    json_path = os.path.join(RESULTS_DIR, f"report_{ts}.json")
    with open(json_path, "w") as fh:
        fh.write(json_content)
    print(f"[+] JSON report:     {json_path}")

    # PDF
    pdf_path = os.path.join(RESULTS_DIR, f"report_{ts}.pdf")
    try:
        generate_pdf(md_content, pdf_path)
        print(f"[+] PDF report:      {pdf_path}")
    except Exception as e:
        print(f"[!] PDF generation failed: {e}")

    # Terminal summary
    print(f"\n{'=' * 60}")
    print(md_content)
    print(f"{'=' * 60}")
